DEFAULT_MODEL = "gpt-4o-mini"
MAX_MESSAGE_LENGTH = 10_000
MAX_THREAD_ID_LENGTH = 128
MAX_EVENT_HISTORY = 512
MAX_OUTPUT_TOKENS = 2048
CHAT_RATE_LIMIT_REQUESTS = 10
CHAT_RATE_LIMIT_WINDOW_SECONDS = 60
